[package]
name = "jujutsu"
version = "0.2.0"
authors = ["Martin von Zweigbergk <martinvonz@google.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Jujutsu (an experimental VCS)"
homepage = "https://github.com/martinvonz/jj"
repository = "https://github.com/martinvonz/jj"
documentation = "https://docs.rs/jujutsu"
readme = "README.md"
keywords = ["VCS", "DVCS", "SCM", "Git", "Mercurial"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "jj"
path = "src/main.rs"

[[bench]]
name = "diff_bench"
harness = false

[workspace]
members = ["lib"]

[dependencies]
atty = "0.2.14"
chrono = "0.4.19"
clap = { version = "3.0.14", features = ["cargo"] }
clap_complete = "3.0.6"
config = "0.11.0"
criterion = "0.3.5"
git2 = "0.16.1"
hex = "0.4.3"
indoc = "1.0.3"
itertools = "0.10.3"
jujutsu-lib = { version = "=0.2.0", path = "lib"}
maplit = "1.0.2"
pest = "2.1.3"
pest_derive = "2.1.0"
rand = "0.8.4"
tempfile = "3.3.0"
textwrap = "0.14.2"
thiserror = "1.0.30"

[dev-dependencies]
test-case = "1.2.3"
regex = "1.5.4"
criterion = "0.3.5"
criterion_bencher_compat = "0.3.4"
